/**
 * Tipos de domínio. Não dependem de UI nem de infraestrutura.
 */

export type Competencia = string; // formato YYYY-MM

export const TRANSACTION_STATUS = ["PENDENTE", "PAGO", "ADIANTADO", "IGNORADO"] as const;
export type TransactionStatus = (typeof TRANSACTION_STATUS)[number];

export const TIPO_LANCAMENTO = ["RECORRENTE", "PARCELADO", "MANUAL"] as const;
export type TipoLancamento = (typeof TIPO_LANCAMENTO)[number];

export const ACCOUNT_TIPO = ["CONTA", "CARTAO", "CARTEIRA"] as const;
export type AccountTipo = (typeof ACCOUNT_TIPO)[number];

export const RECURRENCE_TYPE = ["M", "A"] as const;
export type RecurrenceType = (typeof RECURRENCE_TYPE)[number];

export interface Transaction {
  transaction_id: string;
  template_id: string | null;
  competencia: Competencia;
  descricao: string;
  categoria_id: string;
  valor: number;
  status: TransactionStatus;
  payment_account_id: string | null;
  tipo_lancamento: TipoLancamento;
  /** Set when this transaction was generated by confirming a PurchasePlan; null otherwise. */
  plan_id: string | null;
}

export interface RecurrenceTemplate {
  template_id: string;
  nome: string;
  categoria_id: string;
  payment_account_id: string | null;
  primeira_competencia: Competencia;
  /** Inclusive end month. Absent means the recurrence runs indefinitely. */
  ultima_competencia?: Competencia;
  logo_url?: string;
  icon_id?: string;
  /** M = monthly (every month); A = annual (only in the month of primeira_competencia). */
  recurrence_type: RecurrenceType;
}

/** Derives active status from date range instead of a stored boolean. */
export function isTemplateActive(tpl: RecurrenceTemplate, competencia: Competencia): boolean {
  return (
    tpl.primeira_competencia <= competencia &&
    (!tpl.ultima_competencia || tpl.ultima_competencia >= competencia)
  );
}

/** Returns true when the template is due to generate a transaction for the given competencia. */
export function isDueForCompetencia(tpl: RecurrenceTemplate, competencia: Competencia): boolean {
  if (tpl.recurrence_type !== "A") return true;
  return tpl.primeira_competencia.slice(5) === competencia.slice(5);
}

export interface Category {
  category_id: string;
  nome: string;
  icon_id?: string;
}

export interface Account {
  account_id: string;
  nome: string;
  tipo: AccountTipo;
  icon_id?: string;
  color?: string;
}

export interface Income {
  income_id: string;
  competencia: Competencia;
  descricao: string;
  valor: number;
  icon_id?: string;
}

export interface InvoiceAmount {
  invoice_id: string;
  payment_account_id: string;
  competencia: Competencia;
  valor_real: number;
}

export const DEBT_STATUS = ["PENDENTE", "PAGO"] as const;
export type DebtStatus = (typeof DEBT_STATUS)[number];

export const DEBT_TIPO = ["UNICO", "RECORRENTE", "EMPRESTIMO"] as const;
export type DebtTipo = (typeof DEBT_TIPO)[number];

export interface Debtor {
  debtor_id: string;
  nome: string;
  /** Dígitos com DDI, ex: 5511999999999 — usado no link de cobrança do WhatsApp. */
  telefone?: string;
  icon_id?: string;
}

export interface Debt {
  debt_id: string;
  debtor_id: string;
  competencia: Competencia;
  descricao: string;
  /**
   * For `tipo: "EMPRESTIMO"`, this is a running balance snapshot, not a delta:
   * the root row holds the principal lent, and each subsequent row in the same
   * chain (linked via `parent_debt_id`) holds the remaining balance after that
   * abatement — see `parent_debt_id` doc below.
   */
  valor: number;
  /** Not meaningful for `tipo: "EMPRESTIMO"` — paid/settled state is derived from `valor` instead. */
  status: DebtStatus;
  tipo: DebtTipo;
  /**
   * Only used for `tipo: "EMPRESTIMO"`. Links an abatement row back to the root
   * row of its loan (the first row, which has no `parent_debt_id`). Absent on
   * every other debt and on the root row itself.
   */
  parent_debt_id?: string;
}

export const AMORTIZATION_METHOD = ["PRICE", "SAC", "SEM_JUROS"] as const;
export type AmortizationMethod = (typeof AMORTIZATION_METHOD)[number];

export const RATE_PERIODICITY = ["MENSAL", "ANUAL"] as const;
export type RatePeriodicity = (typeof RATE_PERIODICITY)[number];

export const PURCHASE_PLAN_STATUS = ["RASCUNHO", "SIMULANDO", "CONFIRMADO", "DESCARTADO"] as const;
export type PurchasePlanStatus = (typeof PURCHASE_PLAN_STATUS)[number];

/**
 * A saved simulation for a large, planned purchase (e.g. a car), financed over
 * `numero_parcelas` installments. The installment table itself is never persisted —
 * it is fully derivable from this record's fields and recomputed client-side on
 * demand (see `src/domain/purchasePlanning.ts` / `src/lib/amortization.ts`).
 */
export interface PurchasePlan {
  plan_id: string;
  nome: string;
  descricao?: string;
  /** Principal amount of the purchase, before interest. */
  valor_compra: number;
  /** Interest rate as typed by the user (decimal, e.g. 0.0199), kept in its original periodicity. */
  taxa_juros: number;
  taxa_juros_periodicidade: RatePeriodicity;
  numero_parcelas: number;
  forma_amortizacao: AmortizationMethod;
  /** Desired/confirmed first competencia of the installment schedule. */
  competencia_inicio: Competencia;
  /** Minimum monthly free-balance margin (R$) the user wants to keep — drives the fit verdict. */
  margem_minima: number;
  categoria_id?: string;
  payment_account_id?: string;
  status: PurchasePlanStatus;
  created_at: string;
  updated_at: string;
}
